### PR TITLE
Allow sign if ssn is not on quote itself

### PR DESCRIPTION
**Pull request by vonElfvin**
## What?
- Backfill SSN if present on member

## Why?
- Members in Norway who create bundle through webonboarding cannot activate it later since there is no ssn present on the quote

## Optional checklist
- [ ] Boyscouted
- [ ] Unit tests written
- [ ] Tested locally

### CODE REVIEW

**Review by AlexSJ1990 — APPROVED** [review]

**Review by FredrikAreschoug — COMMENTED** [review]
I think this only will break down the line or? Will we not need to fetch the ssn the strategies as well?

**Comment by johantjellden** [comment]
I don't really understand all of this, why do we have the ssn on member-service but not on the quote? And I think we at least want a test the new logic so that we can understand why it is there. :)

**Comment by johantjellden** [comment]
Hmm. 
1: If you are an existing member in norway and have and existing insurance. You can then go to the web onboarding and only get the other insurance type?
2: When you sign up for that other insurance we don't know your ssn until when you _sign_ with zignsec?

How do you end up in this state? Don't every web-onboarding session get their own memberId? In wich case we cannot use the memberId to lookup your ssn.

**Comment by vonElfvin** [comment]
This issue havn't happened in a while. May as well close and wait for the problem to arise again

**Pull request closed without merging**
